apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: nginx
  newName: alpine # <==== 신규 image name 
  newTag: 3.6 # <==== 신규 tag information
patches:
- relica-count.yaml
- cpu-count.yaml
resources:
- ../../base
