apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: shclub/edu4
#  newName: alpine # <==== 신규 image name 
  newTag: v1 # <==== 신규 tag information
namePrefix: dev-
commonLabels:
  variants: development
bases:
- ../../base
patchesStrategicMerge:
- relica_count.yaml
- cpu_count.yaml
